version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/cloudwan/gohan
    steps:
      - checkout
      - run: go version
      - run: make deps gen lint build
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/cloudwan/gohan
    steps:
      - checkout
      - run: curl -L https://github.com/coreos/etcd/releases/download/v3.1.7/etcd-v3.1.7-linux-amd64.tar.gz -o etcd-v3.1.7-linux-amd64.tar.gz
      - run: tar xzvf etcd-v3.1.7-linux-amd64.tar.gz
      - run: sudo install etcd-v3.1.7-linux-amd64/etcd /usr/bin
      - run: go get github.com/mattn/goveralls
      - run: make test
  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/cloudwan/gohan
    steps:
      - checkout
      - run:
          name: Upload package to Github
          command: |
            go get github.com/karalabe/xgo
            ./tools/crosscompile.sh
            sudo apt-get install -y zip
            curl -L https://github.com/tcnksm/ghr/releases/download/v0.5.0/ghr_v0.5.0_linux_amd64.zip -o ghr_v0.5.0_linux_amd64.zip
            unzip ghr_v0.5.0_linux_amd64.zip
            chmod 0755 ghr
            ./ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -replace pre-release dist/

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
